const articles = [
  {
    id: '1',
    article:
      "**Sizzling SARMAT Showdown: 💥🚀 RUSSIA’s ICBM FUMBLE & the N🕳️uclear Nonsense 🤡💣🔫**\n\n**A NUCLEAR NASTY in RUSSKY LAND! 🇷🇺💔**  \nIn a prompt PANTY-TWISTER, satellite📸 footage is SPILLING the TEA ☕️🍵 on a WILD mishap involving Russia’s SLUMBERING SARMAT Intercontinental BALLISTIC Missiles💥🥵. This mission, which was supposed to be a backdoor DONG SHOW of military power, instead turned into a blooper reel of cosmic proportions 🎥🌌! \n\nThe KREMLIN, ever the DADDY trying to flex, now has some SERIOUS explaining to do as their ERODING BOMB-TOOL faced a less-than-sexy fate 🎭🔥. Reports SIMMERING through the grapevine suggest that this janky JOLT of a missile didn’t just trundle on its merry way, but instead EXPLODED into a fiery MESS 💥💔, shaking the foundations of their vaunted nuclear bravado 🦸‍♂️⚡️. \n\n**WHAT went DOWN? 💣👀**  \nAccording to satellite surveillance, it seems this CRASH LANDING 🎈💥 was no mere fender bender; it was an all-out CATASTROPHIC FAIL that has left the RUSSIAN military utterly red-faced and questioning ONCE AGAIN if they’re still sporting any PANTS in the global military lounge 💃😳. The deadly display of their intercontinental show-off has caused more than a little GASP and GAWK among international onlookers 🍿👀, raising eyebrows hotter than a jalapeño 🍓🔥. \n\nThese unfortunate *FIREWORKS* happened earlier this month 💥🚀, instantly putting a dent in the Kremlin's flashing nuclear sabers as they tried to swagger about power during high-stake fu—*ahem*, negotiations 🤭✨.  \n**DICKin into DEPTHS of DEBAUCHERY** 💦🔥  \nSo, what now? With this catastrophic DONG-PULVERIZATION now thrust into the public eye, doubts RESOUND about *who really has the biggest miss-ILE* between the sheets of the cold war! 🌍📉 As it turns out, that hard power play may be not so hard after all; speculation floods through the military circuits like a thirsty ho’s lips at a frat party 🍻🤪. \n\n**WHATS THE CALL? 🤷‍♂️💁‍♀️**  \nIf you're a PATRIOT of PRICKLY politics 🇺🇸💔, it’s time to get your reports in line! This fresh SKID MARK on Mother Russia’s reputation is nothing short of a raging red flag 🚩—with potential implications hotter than a TWO-HANDED TONGUE 🎇🔥! 🚫💣 Sochka, do you think that missile really went off, or was it just a wild party at the Kremlin gone off the rails? 🥳🤪\n\nIn conclusion, STAY tuned! ‘Cuz in this never-ending game of international make-believe, it seems the only thing exploding is RUSSIA’s credibility. Buckle up, buttercup, this ride ain't over yet! 🤡🍿💥",
    url: 'https://www.washingtonpost.com/world/2024/09/23/russia-sarmat-icbm-disaster/',
    urlToImage:
      'https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/OKUGQ3G5AIXXWE7P6BV5D3KQEI.JPG&w=1440',
    publishedAt: '2024-09-23T20:16:45Z',
    likes: 0,
    title:
      'Sizzling SARMAT Showdown: RUSSIA’s ICBM FUMBLE & the N🕳️uclear Nonsense 🤡💣🔫',
  },
];
export { articles };
